<a href="https://colab.research.google.com/github/Abhishek1shrivastava/Machine-learning/blob/main/machine_learning_day03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Home price prediction(linear regression with multiple variable)***

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
data = {'area':[2600,3000,3200,3600,4000],'bedrooms':[3,4,np.NaN,3,5],'age':[20,15,18,30,8],'price':[550000,565000,610000,595000,760000]}
df=pd.DataFrame(data)
print(df)




   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000


In [14]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
print(median_bedrooms)

3


In [15]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
print(df)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000


In [17]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [18]:
reg.intercept_

383724.9999999998

In [20]:
reg.predict([[3000,3,21]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([574075.])

In [21]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

***salary prediction based on hiring dataset***



In [27]:
!pip install word2number
from inspect import modulesbyfile
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n
d = pd.read_csv('/hiring.csv')
d.head(5)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [29]:
d.experience = d.experience.fillna('zero')
d.head(5)


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [34]:
import math
median_test_score = math.floor(d['test_score(out of 10)'].mean())
print(median_test_score)
d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(median_test_score)
d.head(5)

7


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [41]:
d['experience'] = d['experience'].astype(str).apply(w2n.word_to_num)
d.head(5)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [45]:
reg  = linear_model.LinearRegression()
reg.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])

LinearRegression()

In [46]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [48]:
reg.intercept_

14992.65144669314

**2 yr experience, 9 test score, 6 interview score**

In [49]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

**12 yr experience, 10 test score, 10 interview score**

In [50]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])