<a href="https://colab.research.google.com/github/Abhishek1shrivastava/Machine-learning/blob/main/pickle_and_joblib05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

data = {"Area":[2600,3000,3200,3000,4000],"Price":[550000,565000,610000,660000,725000]}
df = pd.DataFrame(data)
print(df)


   Area   Price
0  2600  550000
1  3000  565000
2  3200  610000
3  3000  660000
4  4000  725000


In [6]:
model = linear_model.LinearRegression()
model.fit(df[['Area']],df.Price)


LinearRegression()

In [8]:
model.coef_

array([120.70895522])

In [9]:
model.intercept_


240559.70149253728

In [11]:
model.predict([[3300]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([638899.25373134])

In [12]:
import pickle


In [13]:
with open('model_pickle','wb') as f:
  pickle.dump(model,f)

In [14]:
with open('model_pickle','rb') as f:
  mp = pickle.load(f)

In [15]:
mp.predict([[3300]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([638899.25373134])

In [17]:
!pip install joblib

In [20]:
!pip install sklearn.externals

ERROR: Could not find a version that satisfies the requirement sklearn.externals (from versions: none)
ERROR: No matching distribution found for sklearn.externals


In [21]:
import joblib

In [22]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [23]:
joblib.load('model_joblib')

LinearRegression()

In [25]:
mj = joblib.load('model_joblib')

In [26]:
mj.predict([[3300]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([638899.25373134])